/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
      {
        "_edit_event_id": "0.5340332929499954",
        "selector": ".U1",
        "center": {
          "x": 1.746095876782892,
          "y": 2.475930830364173
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.6227520277242637",
        "selector": ".R1",
        "center": {
          "x": 1.9299614017752447,
          "y": 7.7243658318277015
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.698321896197684",
        "selector": ".C2",
        "center": {
          "x": 2.0952744859109593,
          "y": -3.519538247005859
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.694421244981795",
        "selector": ".C3",
        "center": {
          "x": 9.701708433778615,
          "y": -8.173734229851792
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.14577610722156287",
        "selector": ".U2",
        "center": {
          "x": -10.924629278567146,
          "y": 1.0619322663050923
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.6146476940172356",
        "selector": ".JP1",
        "center": {
          "x": 14.285834859193642,
          "y": -1.0621258219412475
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.11940755994421504",
        "selector": ".J1",
        "center": {
          "x": 1.5803934242670934,
          "y": -10.745920624907164
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.7478320278304127",
        "selector": ".JP3",
        "center": {
          "x": -10.015882522757462,
          "y": -0.29254949341672365
        },
        "relative_to": "group_center"
      }
    ],
  edit_events: [],
  manual_trace_hints: [
    {
      "pcb_port_selector": ".C2 > .left",
      "offsets": [
        {
          "x": -0.46567037894333296,
          "y": -3.0697423658834904,
          "via": false
        }
      ]
    },
    {
      "pcb_port_selector": ".U1 > .VCC",
      "offsets": [
        {
          "x": -0.87561338712114,
          "y": -2.3188874876950147,
          "via": false
        }
      ]
    }
  ],
}
