/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
      {
        "_edit_event_id": "0.5340332929499954",
        "selector": ".U1",
        "center": {
          "x": 0.9564573970858952,
          "y": 1.1525186859002456
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.6227520277242637",
        "selector": ".R1",
        "center": {
          "x": 4.508803742867368,
          "y": 6.548303105361264
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.698321896197684",
        "selector": ".C2",
        "center": {
          "x": 2.0508160789814376,
          "y": -5.349987759684872
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.694421244981795",
        "selector": ".C3",
        "center": {
          "x": 2.0767169908372143,
          "y": -7.634963326858433
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.6146476940172356",
        "selector": ".JP1",
        "center": {
          "x": 7.200983118705036,
          "y": -0.05878186520397222
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.11940755994421504",
        "selector": ".J1",
        "center": {
          "x": -0.15501613420420313,
          "y": -10.228511110983444
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.7478320278304127",
        "selector": ".JP3",
        "center": {
          "x": -5.994795260596689,
          "y": -0.3929636504365792
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.767945008702394",
        "selector": ".Q1",
        "center": {
          "x": 0.5764983901285063,
          "y": 9.292442544944734
        },
        "relative_to": "group_center"
      }
    ],
  edit_events: [],
  manual_trace_hints: [
    {
      pcb_port_selector: ".C2 > .left",
      offsets: [
        {
          x: -0.46567037894333296,
          y: -3.0697423658834904,
          via: false,
        },
      ],
    },
    {
      pcb_port_selector: ".U1 > .VCC",
      offsets: [
        {
          x: -0.87561338712114,
          y: -2.3188874876950147,
          via: false,
        },
      ],
    },
    {
      pcb_port_selector: ".U1 > .BOUT2_1",
      offsets: [
        {
          x: -3.9063496567089153,
          y: 2.917975289802527,
          via: false,
        },
      ],
    },
  ],
}
