/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
      {
        "_edit_event_id": "0.5340332929499954",
        "selector": ".U1",
        "center": {
          "x": 0.16047563200552872,
          "y": 3.0045970734593066
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.6227520277242637",
        "selector": ".R1",
        "center": {
          "x": 7.358162122442685,
          "y": 4.4487274659076945
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.698321896197684",
        "selector": ".C2",
        "center": {
          "x": 12.069849623214214,
          "y": 3.946139621117802
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.694421244981795",
        "selector": ".C3",
        "center": {
          "x": 9.701708433778615,
          "y": -8.173734229851792
        },
        "relative_to": "group_center"
      },
      {
        "_edit_event_id": "0.14577610722156287",
        "selector": ".U2",
        "center": {
          "x": -10.924629278567146,
          "y": 1.0619322663050923
        },
        "relative_to": "group_center"
      }
    ],
    edit_events: [],
    manual_trace_hints: [
      {
        "pcb_port_selector": ".C2 > .left",
        "offsets": [
          {
            "x": 7.35804070244359,
            "y": -1.1224636088241784,
            "via": false
          },
          {
            "x": 6.5855467594075385,
            "y": -0.5782065125942317,
            "via": true
          },
          {
            "x": 1.8803563790970428,
            "y": 4.794137727611036,
            "via": true
          }
        ]
      }
    ]
}